pipelines:
  default:
     - step:
         name: Deploy to production
         deployment: production
         script:
           - echo "Deploying to production environment"
           - pipe: atlassian/ssh-run:0.2.2
             variables:
               SSH_USER: 'root'
               SERVER: '144.217.240.139'
               COMMAND: "cd lippia-report-server-front && docker-compose up --quiet-pull"