pipelines:
  branches:
    master:
      - step:
         name: Generate Production docker image
         services:
           - docker
         script:
           - export IMAGE_NAME=crowdar/report-server-front:$BITBUCKET_COMMIT
           - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASSWORD
           - docker build -f Dockerfile.production -t $IMAGE_NAME .
           - docker push $IMAGE_NAME
           - export IMAGE_NAME=crowdar/report-server-front:latest
           - docker build -f Dockerfile.production -t $IMAGE_NAME .
           - docker push $IMAGE_NAME
      - step:
         name: VPS1 Deploy
         deployment: production
         script:
           - pipe: atlassian/ssh-run:0.2.2
             variables:
               SSH_USER: 'root'
               SERVER: '144.217.90.28'
               COMMAND: "cd lippia-report-server-front && docker pull crowdar/report-server-front && docker-compose -f docker-compose.yml up -d --build"
    staging:
      - step:
         name: Generate RC docker image
         services:
           - docker
         script:
           - export IMAGE_NAME=crowdar/report-server-front:RC-staging
           - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASSWORD
           - docker build -f Dockerfile.production -t $IMAGE_NAME .
           - docker push $IMAGE_NAME
      - step:
         name: VPS2 Deploy
         deployment: production
         script:
           - pipe: atlassian/ssh-run:0.2.2
             variables:
               SSH_USER: 'root'
               SERVER: '144.217.240.139'
               COMMAND: "cd lippia-report-server-front && docker pull crowdar/report-server-front:RC-staging && docker-compose -f docker-compose.yml up -d --build"

definitions:
  services:
    docker:
      memory: 2048