version: "3"

services:
  client:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    tty: true
  api_rs_report:
    image: crowdar/report-server-backend:3.2.1.1
    environment:
      - DB_URI=mongodb://root:Crowdar2019@vps2.crowdaronline.com:27017/admin
      - REDIS_ACTIVE=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8083:80
