version: "3"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    restart: always
